/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData heart_full = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData fill_star = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData arrowBack = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData openField = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData Shower = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData dressing = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData inventory = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData parking = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData countOfFields = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData s_all = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData map_arrow = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData exit = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData connect = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData ring = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData reservation = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData map_1 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData field = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData day = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe81b, fontFamily: _kFontFam);
}
